apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusterapplicationloadbalancers.ingress.k8s.aws
spec:
  group: ingress.k8s.aws
  names:
    kind: ClusterApplicationLoadBalancer
    plural: clusterapplicationloadbalancers
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            attributes:
              properties:
                accessLogs:
                  properties:
                    s3:
                      properties:
                        bucket:
                          type: string
                        enabled:
                          type: boolean
                        prefix:
                          type: string
                      type: object
                  required:
                  - s3
                  type: object
                deletionProtection:
                  properties:
                    enabled:
                      type: boolean
                  required:
                  - enabled
                  type: object
                idleTimeout:
                  properties:
                    timeoutSeconds:
                      format: int64
                      maximum: 4000
                      minimum: 1
                      type: integer
                  required:
                  - timeoutSeconds
                  type: object
                routing:
                  properties:
                    http2:
                      properties:
                        enabled:
                          type: boolean
                      type: object
                  type: object
              type: object
            ipAddressType:
              enum:
              - ipv4
              - dualstack
              type: string
            schema:
              enum:
              - internal
              - internet-facing
              type: string
            securityGroups:
              items:
                type: string
              minItems: 1
              type: array
            subnetMappings:
              items:
                properties:
                  subnetID:
                    type: string
                required:
                - subnetID
                type: object
              minItems: 2
              type: array
            tags:
              type: object
          required:
          - subnetMappings
          - securityGroups
          type: object
        status:
          properties:
            dnsName:
              type: string
            loadBalancerARN:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
