apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: subnet-0d2bab64,subnet-9c569ce7
    alb.ingress.kubernetes.io/security-groups: sg-ccaacaa5
    alb.ingress.kubernetes.io/tags: Environment=dev1,ProductCode=PRD999,InventoryCode=echo-app
spec:
  rules:
  - host: aaaaaa.josh-test-dns.com
    http:
      paths:
      - path: /
        backend:
          serviceName: echoserver
          servicePort: 80
