apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "nginx-ingress"
  namespace: "2048-game"
  annotations:
    ingress.ticketmaster.com/scheme: internal
    ingress.ticketmaster.com/subnets: subnet-a4f0098e,subnet-457ed533,subnet-95c904cd
    ingress.ticketmaster.com/security-groups: sg-723a380a,sg-a6181ede,sg-a5181edd 
  labels:
    app: 2048-nginx-ingress
spec:
  rules:
  - host: 2048.nonprod-tmaws.io
    http:
      paths:
      - path: /
        backend:
          serviceName: "service-2048"
          servicePort: 80
